name: ThreeQuartermoon
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0b09'
    - '#e8c984'
    - '#655632'
    - '#cbb380'
    - '#b09a66'
  brandStrength: 0.5085271836724132
  lightness: 0.695421026321128
  saturation: 0.5500806418713182
  rhythmicContrast: 0.12192413629963994
purpose: []
